apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: expense

data:
 DB_HOST: "mysql" 
---
apiVersion: apps/v1     
kind: Deployment       
metadata:
  name: backend
  namespace: expense            
  labels:                
    app: backend
    tier: api
    project: expense
spec:
  replicas: 2            
  selector:              
    matchLabels:
      app: backend
      tier: api 
      project: expense 

  template:              
    metadata:
      labels:            
        app: backend
        tier: api
        project: expense 
    spec:
      containers:
      - name: backend
        image: basavaraj0509/backend:v1
        resources:
          requests: 
           cpu: 100m
           memory: 128Mi
          limits:                 #limits should be greaterthan equal to request not less than
           cpu: 100m
           memory: 128Mi 
        envFrom:              #connecting to database 
        - configMapRef: 
            name: backend-config
         # readinessProbe ensures the container is ready to accept traffic after startup.
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15 #probes use a 15-second initial delay to allow the backend to initialize,
          periodSeconds: 10 #check the connection every 10 seconds thereafter.
        # livenessProbe ensures the container is restarted if it becomes unresponsive.
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
---
kind: Service
apiVersion: v1 

metadata: 
  name: backend
  namespace: expense
 
spec: 
  selector:
    app: backend
    tier: api
    project: expense
  ports: 
  - name: backend-port 
    protocol: TCP
    port: 8080  #service port
    targetPort: 8080 #container port (exposeoutside)
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: backend
 namespace: expense
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: backend
 minReplicas: 1
 maxReplicas: 10
 targetCPUUtilizationPercentage: 15 #in real time 75