apiVersion: apps/v1     
kind: Deployment       
metadata:
  name: mysql
  namespace: expense            
  labels:                
    app: mysql
    tier: db
spec:
  replicas: 1            
  selector:              
    matchLabels:
      app: mysql
      tier: db  

  template:              
    metadata:
      labels:            
        app: mysql
        tier: db
    spec:
      containers:
      - name: mysql
        image: basavaraj0509/mysql:v1

# ---
# kind: Service
# apiVersion: v1 

# metadata: 
#   name: nginx 

# spec: 
#   selector:
#     app: nginx
#     tier: frontend
#   ports: 
#   - name: nginx-service-port 
#     protocol: TCP
#     port: 80 
#     targetPort: 80  